### ISSUE TITLE
Turn off quick edit option

### ISSUE THREAD

**Issue by ghost** [mahaloatchaboy/CrisisResponse#18]
RFI, Watch Log, Message Traffic

**Comment by chanm003** [comment]
You mean for the back end lists?
- /Lists/WatchLog
- /Lists/MessageTraffic
- /Lists/RFI

**Comment by chanm003** [comment]
@weihenstephaner says it is okay to have the "quick edit" option for the backend lists, since normal users won't be navigating there.

Quick Edit option continues to be hidden on the webpart pages
- SitePages/socc.aspx
- SitePages/soac.aspx
- SitePages/sotg.aspx
- SitePages/comms.aspx
- SitePages/excon.aspx
